### ISSUE TITLE
list of domains to test

### ISSUE THREAD

**Issue by pixelpaulaus** [googleapis/nodejs-web-risk#291]
it would be great to have a list of domains to use in testing, which return different results, so we can test all possibilities.

**Comment by bcoe** [comment]
@pixelpaulaus this sounds like a good suggeston.

To make a suggestoin to the team, a better place to open a ticket, would be in the issue tracker [here](https://cloud.google.com/support/docs/issue-trackers). This will get to the WebRisk team, rather than the folks who main tain the client libraries.
